import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  notesSidebar: [
    'index',
    {
      type: 'category',
      label: 'TypeScript',
      items: [
        'typescript/intro',
        {
          type: 'category',
          label: 'Core Concepts',
          items: [{type: 'autogenerated', dirName: 'typescript/core-concepts'}],
        },
        {
          type: 'category',
          label: 'Exercism Problems',
          items: [{type: 'autogenerated', dirName: 'typescript/exercism-problems'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Python',
      items: [
        'python/intro',
        {
          type: 'category',
          label: 'Exercism Problems',
          items: [{type: 'autogenerated', dirName: 'python/exercism-problems'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'LLD',
      items: [
        'lld/intro',
        {
          type: 'category',
          label: 'Parking Lot',
          items: [
            'lld/parking-lot/strategy-pattern',
            'lld/parking-lot/factory-method',
            'lld/parking-lot/decorator-pattern',
            'lld/parking-lot/observer-pattern',
            'lld/parking-lot/singleton-pattern',
            // 'lld/parking-lot/parking-lot-lld',
          ],
        },
          // {
          //   type: 'category',
          //   label: 'Weather App',
          //   items: [{type: 'autogenerated', dirName: 'lld/weather-app'}],
          // },
        // {
        //   type: 'category',
        //   label: 'Vending Machine',
        //   items: [{type: 'autogenerated', dirName: 'lld/vending-machine'}],
        // },
      ],
    },
    {
      type: 'category',
      label: 'JavaScript',
      items: [
        'javascript/intro',
        {
          type: 'category',
          label: 'Core Concepts',
          items: [{type: 'autogenerated', dirName: 'javascript/core-concepts'}],
        },
        {
          type: 'category',
          label: 'Exercism Problems',
          items: [{type: 'autogenerated', dirName: 'javascript/exercism-problems'}],
        },
      ],
    },
  ],
};

export default sidebars;
